name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.2.10

      - name: Build project
        run: |
          deno install -f --name silverbullet --unstable-kv --unstable-worker-options -A https://github.com/silverbulletmd/silverbullet/releases/download/0.10.4/silverbullet.js --global
          deno task build

      - name: Archive built file
        run: |
          mkdir -p artifacts
          cp dailyquote.plug.js ./artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
